### ISSUE TITLE
Enable Swagger Docs

### ISSUE THREAD

**Issue by crankynetman** [esnet-security/SCRAM#86]
We should publish an OpenAPI spec and Swagger Docs.

**Comment by samoehlert** [comment]
I think we should also look at this at the same time https://github.com/Friskes/drf-spectacular-websocket to basically do swagger but for our websockets portions

**Comment by samoehlert** [comment]
Or not:

```533.1 The conflict is caused by:
533.1     The user requested channels==3.0.5
533.1     drf-spectacular-websocket 1.3.0 depends on channels>=4.0.0
```

however, `django-eventstream` cannot use channels >=4.0.0
